logging:
  level:
    root: info
    org.nutz: debug
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
server:
  port: 8081
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true